<?xml version="1.0"?>
<robot name="gripper" xmlns:xacro="http://ros.org/wiki/xacro">

 <xacro:include filename="$(find mybot_description)/urdf/gripper.gazebo" />

  <property name="PI" value="3.1415926535897931"/>

  <property name="chassisHeight" value="0.05"/>
  <property name="chassisLength" value="0.15"/>
  <property name="chassisWidth" value="0.1"/>
  <property name="chassisMass" value="0"/>

  <property name="casterRadius" value="0.025"/>
  <property name="casterMass" value="2.5"/>


  <property name="wheelWidth" value="0.025"/>
  <property name="wheelRadius" value="0.05"/>
  <property name="wheelPos" value="-0.15"/>
  <property name="wheelMass" value="2.5"/>

  <property name="EndEffectorHeight" value="0.55"/>

  <property name="baseHeight" value="0.15"/>
  <property name="baseLength" value="0.01"/>
  <property name="baseWidth" value="0.08"/>
  <property name="baseMass" value="2.7"/>

  <property name="link1Height" value="0.1"/>
  <property name="link1Length" value="0.2"/>
  <property name="link1Width" value="0.02"/>
  <property name="link1Mass" value="2.9"/>

  <property name="link2Height" value="0.12"/>
  <property name="link2Length" value="0.02"/>
  <property name="link2Width" value="0.02"/>
  <property name="link2Mass" value="2.2"/>

  <property name="tipHeight" value="0.3"/>
  <property name="tipLength" value="0.05"/>
  <property name="tipWidth" value="0.03"/>
  <property name="tipMass" value="2.07"/>
  <property name="tip_close_limit" value="0.05"/> 
  <property name="tip_open_limit" value="1.0"/> 

  <property name="cameraSize" value="0.025"/>
  <property name="cameraMass" value="0.05"/>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
      iyy="${m*(x*x+z*z)/12}" iyz = "0"
      izz="${m*(x*x+z*z)/12}"/>
  </xacro:macro>

<xacro:macro name="gripper_spawn">
<link name='gripper_link'>
  <collision>
    <!-- origin xyz="0 -0.012 0" rpy="0 0 ${PI/2}"/ -->
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <!-- mesh filename="package://mybot_description/meshes/base_motor.DAE"/ -->
      <mesh filename="package://mybot_description/meshes/base.DAE"/>
    </geometry>
  </collision>
  <visual>
  <!-- origin xyz="0 -0.012 0" rpy="0 0 ${PI/2}"/ -->
  <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
<!-- mesh filename="package://mybot_description/meshes/base_motor.DAE"/ -->
<mesh filename="package://mybot_description/meshes/base.DAE"/>
    </geometry>
   <material name="black"/>
  </visual>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${baseMass}"/>
    <xacro:box_inertia m="${baseMass}" x="${baseLength}" y="${baseWidth}" z="${baseHeight}"/>
  </inertial>
</link>

<joint name="base_to_link1" type="fixed">
  <parent link="gripper_link"/>
  <child link="link1"/>
 <!-- origin xyz="0 0 -0.07" rpy="0 0 ${PI/2}"/ -->
 <origin xyz="0 0.005 -0.07" rpy="0 0 ${PI/2}"/>
</joint>

<link name='link1'>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://mybot_description/meshes/link1.DAE"/>
    </geometry>
  </collision>
  <visual>
   <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
<mesh filename="package://mybot_description/meshes/link1.DAE"/>
    </geometry>
   <material name="black"/>
  </visual>
  <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${link1Mass}"/>
    <xacro:box_inertia m="${link1Mass}" x="${link1Length}" y="${link1Width}" z="${link1Height}"/>
  </inertial>
</link>

<joint name="link1_to_link2" type="fixed">
    <origin xyz="0.104 0 0" rpy="0 0 ${PI/2}"/>
  <parent link="link1"/>
  <child link="link2"/>
</joint>

<link name='link2'>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
    <geometry>
      <mesh filename="package://mybot_description/meshes/link2.DAE"/>
    </geometry>
  </collision>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 ${PI}"/>
    <geometry>
<mesh filename="package://mybot_description/meshes/link2.DAE"/>
    </geometry>
   <material name="black"/>
  </visual>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${link2Mass}"/>
    <xacro:box_inertia m="${link2Mass}" x="${link2Length}" y="${link2Width}" z="${link2Height}"/>
  </inertial>
</link>

<joint name="left_tip_hinge" type="revolute">
  <parent link="link2"/>
  <child link="left_tip"/>
<origin xyz="0.0125 0.001 0.0005" rpy="0 0 -${PI/2}" />
  <axis xyz="0 0 1" rpy="0 0 0" />
  <!-- limit effort="100" velocity="5" lower="-0.037" upper="0.6" / -->
  <!-- limit effort="100" velocity="5" lower="-0.2" upper="0.6" / -->
  <limit effort="100" velocity="1" lower="${tip_close_limit}" upper="${tip_open_limit}" />
  <joint_properties damping="0.0" friction="10.0"/>
</joint>

<link name='left_tip'>
  <collision>
   <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <mesh filename="package://mybot_description/meshes/tip.DAE"/>
    </geometry>
  </collision>
  <visual>
   <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
<mesh filename="package://mybot_description/meshes/tip.DAE"/>
    </geometry>
   <material name="black"/>
  </visual>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${tipMass}"/>
    <xacro:box_inertia m="${tipMass}" x="${tipLength}" y="${tipWidth}" z="${tipHeight}"/>
  </inertial>
</link>

<joint name="right_tip_hinge" type="revolute">
  <parent link="link2"/>
  <child link="right_tip"/>
<origin xyz="-0.0125 0.001 0.0005" rpy="0 0 ${PI/2}" />
  <axis xyz="0 0 1" rpy="0 0 0" />
  <!-- limit effort="100" velocity="5" lower="-0.6" upper="0.037" / -->
  <!-- limit effort="100" velocity="5" lower="-0.6" upper="0.2" / -->
  <limit effort="100" velocity="1" lower="-${tip_open_limit}" upper="-${tip_close_limit}" />
  <joint_properties damping="0.0" friction="10.0"/>
</joint>

<link name='right_tip'>
  <collision>
   <origin xyz="0 0 0" rpy="0 ${PI} 0" />
    <geometry>
      <mesh filename="package://mybot_description/meshes/tip.DAE"/>
    </geometry>
  </collision>
  <visual>
   <origin xyz="0 0 0" rpy="0 ${PI} 0" />
    <geometry>
<mesh filename="package://mybot_description/meshes/tip.DAE"/>
    </geometry>
   <material name="black"/>
  </visual>
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${tipMass}"/>
    <xacro:box_inertia m="${tipMass}" x="${tipLength}" y="${tipWidth}" z="${tipHeight}"/>
  </inertial>
</link>

<joint name="base_to_camera" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
  <parent link="gripper_link"/>
  <child link="camera"/>
</joint>

<link name="camera">
  <collision>
    <origin xyz="${cameraSize/2} 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize*2} ${cameraSize/2} ${cameraSize/2}"/>
    </geometry>
  </collision>
  <visual>
   <origin xyz="${cameraSize/2}  0 0" rpy="0 0 0"/>
    <geometry>
      <box size="${cameraSize*2} ${cameraSize/2} ${cameraSize/2}"/>
    </geometry>
    <material name="black"/>
  </visual>
  <inertial>
    <mass value="${cameraMass}" />
    <origin xyz="0.025 0 0" rpy="0 0 0"/>
    <xacro:box_inertia m="${cameraMass}" x="${cameraSize*2}" y="${cameraSize/2}" z="${cameraSize/2}" />
  </inertial>
</link>

<transmission name="left_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="left_tip_hinge">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
 </joint>
  <actuator name="$left_Motor">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="right_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="right_tip_hinge">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
 </joint>
  <actuator name="$right_Motor">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<!--adding the gripper tag-->
<gazebo>
  <gripper name="gripper">
    <grasp_check>
      <attach_steps>2</attach_steps>
      <detach_steps>5000</detach_steps>
      <min_contact_count>1</min_contact_count>
    </grasp_check>
    <!--gripper_link>right_tip</gripper_link-->
    <!--gripper_link>left_tip</gripper_link-->
    <gripper_link>link2</gripper_link>
    <palm_link>link2</palm_link>
  </gripper>
</gazebo>
    <xacro:gripper_gazebo />
  </xacro:macro>
</robot>
