<?xml version="1.0"?>
<robot name="gripper_gazebo" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="chassisHeight" value="0.05"/>
  <xacro:property name="chassisLength" value="0.15"/>
  <xacro:property name="chassisWidth" value="0.1"/>
  <xacro:property name="chassisMass" value="0"/>

  <xacro:property name="wheelWidth" value="0.025"/>
  <xacro:property name="wheelRadius" value="0.05"/>
  <xacro:property name="wheelPos" value="-0.15"/>
  <xacro:property name="wheelMass" value="2.5"/>

  <!-- Gazebo plugin for ROS Control -->
  <!--gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/gripper</robotNamespace>
    </plugin>
  </gazebo-->

  <xacro:gripper_gazebo />

  <xacro:macro name="gripper_gazebo">

    <xacro:gripper_camera_gazebo prefix="ur5_arm_gripper_camera"/>
    
    <xacro:gripper_motor_gazebo prefix="ur5_arm_gripper" />

    <gazebo reference="ur5_arm_gripper_link_2">
      <material>Gazebo/Black</material>
      <kp>10000.0</kp>
      <kd>100.0</kd>
      <mu1>10.0</mu1>
      <mu2>1.0</mu2>
      <fdir1>1 1 1</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.00</minDepth>
    </gazebo>

    <gazebo reference="ur5_arm_gripper_left_tip">
      <material>Gazebo/Black</material>
      <kp>10000.0</kp>
      <kd>100.0</kd>
      <mu1>10.0</mu1>
      <mu2>1.0</mu2>
      <fdir1>1 1 1</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.00</minDepth>
    </gazebo>

    <gazebo reference="ur5_arm_gripper_right_tip">
      <material>Gazebo/Black</material>
      <kp>10000.0</kp>
      <kd>100.0</kd>
      <mu1>10.0</mu1>
      <mu2>1.0</mu2>
      <fdir1>1 1 1</fdir1>
      <maxVel>1.0</maxVel>
      <minDepth>0.00</minDepth>
    </gazebo>

  </xacro:macro>

  <!-- sensor plugins -->
  <xacro:macro name="gripper_camera_gazebo" params="prefix">
    <!-- camera -->
    <gazebo reference="${prefix}_link">
      <sensor type="camera" name="${prefix}">
        <update_rate>30.0</update_rate>
        <camera name="${prefix}">
          <horizontal_fov>1.5708</horizontal_fov>
          <image>
            <width>1920</width>
            <height>1080</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <!-- Noise is sampled independently per pixel on each frame.
                 That pixel's noise value is added to each of its color
                 channels, which at that point lie in the range [0,1]. -->
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="gripper_${prefix}_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>30.0</updateRate>
          <cameraName>usb_cam</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>/${prefix}/camera_info</cameraInfoTopicName>
          <frameName>gripper_camera</frameName>
	  <hackBaseline>0.07</hackBaseline>
          <distortion_k1>0.0</distortion_k1>
          <distortion_k2>0.0</distortion_k2>
          <distortion_k3>0.0</distortion_k3>
          <distortion_t1>0.0</distortion_t1>
          <distortion_t2>0.0</distortion_t2>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="gripper_motor_gazebo" params="prefix">

    <gazebo>
      <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100</updateRate>
        <leftJoint>${prefix}_link_2_left_tip_joint</leftJoint>
        <rightJoint>${prefix}_link_2_right_tip_joint</rightJoint>
        <wheelSeparation>${chassisWidth+wheelWidth}</wheelSeparation>
        <wheelDiameter>${2*wheelRadius}</wheelDiameter>
        <torque>20</torque>
        <commandTopic>${prefix}/cmd_vel</commandTopic>
        <odometryTopic>odom</odometryTopic>
        <odometryFrame>odom</odometryFrame>
        <robotBaseFrame>base_footprint</robotBaseFrame>
      </plugin>
    </gazebo>
  </xacro:macro>

</robot>
