teleop_twist_joy:
  axis_linear: 1
  scale_linear: 1.0
  scale_linear_turbo: 2.0
  axis_angular: 0
  scale_angular: 3.4
  scale_angular_turbo: 6.9
  enable_button: 1
  enable_turbo_button: 2
joy_node: 
  deadzone: 0.1
  autorepeat_rate: 20

